[default_session]
startup_script = "nvim -c ':Telescope find_files'"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "tmux config"
path = "~/dotfiles/tmux/.config/tmux"
startup_command = "nvim tmux.conf"
