tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "wix/brew"

cask_args appdir: "/Applications"

brew "ack"
brew "applesimutils"
brew "azure-cli"
brew "bat"
brew "binutils"
brew "chruby"
brew "cocoapods"
brew "coreutils"
brew "diffutils"
brew "direnv"
brew "ffmpeg"
brew "findutils"
brew "fzf"
brew "gawk"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "gnu-which"
brew "gnupg"
brew "grep"
brew "gzip"
brew "jq"
brew "moreutils"
brew "neovim"
brew "node"
brew "obsidian"
brew "ollama"
brew "pixi"
brew "python"
brew "pyenv"
brew "rename"
brew "rsync"
brew "ruby-install"
brew "rust"
brew "screen"
brew "starship"
brew "stow"
brew "terraform"
brew "tmux"
brew "tree"
brew "vim"
brew "watchman"
brew "wget"
brew "yarn"
brew "zlib"
brew "zplug"
brew "zsh"
brew "zoxide"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

cask "1password"
cask "airpass"
cask "alacritty"
cask "alfred"
cask "docker"
cask "dozer"
cask "expo-orbit"
cask "flux"
cask "font-hack"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "istat-menus"
cask "kap"
cask "kicad"
cask "lulu"
cask "obsidian"
cask "pgadmin4"
cask "postman"
# cask "prusaslicer"
cask "qgis"
cask "sketch"
cask "syncthing"
cask "the-unarchiver"
cask "transmission"
cask "ultimaker-cura"
cask "visual-studio-code"


# initialize yabai and skhd
# yabai --install-service
# yabai --start-service
# skhd --install-service
# skhd --start-service